@startuml generealComponentDiagram

folder "Pages" {
component MainPage
component CategoryPage
component ChosenCardsPage
component AnimationPage
component NotFoundPage

MainPage --> ChosenCardsPage 
CategoryPage - ChosenCardsPage
ChosenCardsPage ---> AnimationPage
AnimationPage --> MainPage
}

folder "Components"{
component AnimationsPreview
component Card
component CardContainer
component Character 
component FormFieldAnimationPage 
component LinkButton 
component LinkToPage
component Logo
component TopContainer

AnimationsPreview ..> AnimationPage
Card –> CardContainer
CardContainer ..> CategoryPage
FormFieldAnimationPage -> AnimationsPreview
LinkButton ..> CategoryPage
LinkButton ..> ChosenCardsPage
LinkButton ..> MainPage
LinkButton ..> NotFoundPage
LinkButton -> AnimationsPreview
LinkToPage ..> ChosenCardsPage
Logo -> TopContainer
Logo ...> MainPage
Logo ...> NotFoundPage
TopContainer ....> CategoryPage
TopContainer ....> ChosenCardsPage
TopContainer .....> AnimationPage
}

folder Animations {
    component [All the animation components]
   
   Animations .....> AnimationsPreview
    
}

@enduml